$(document).ready(function(){
    $("#Waiting").load(function(){
		$.ajax({
			type:"POST",
			url:"seeAuthority",
			success:function(data){console.log(data);},
			data:{
				target:'0',
			}
		});
	});
})
$(function(){ 
　　$("#Waiting").load(function(){
		$.ajax({
			type:"POST",s
			url:"seeAuthority",
			success:function(data){console.log(data);},
			data:{
				target:'0',
			}
		});
　　}); 
})
$(function(){
	$("#Waiting").click(function(){
		$.ajax({
			type:"POST",
			url:"seeAuthority",
			dataType:"",
			//success:
			data:{
				target:'1',
			}
		});
	});
})
$(function(){
	$("#Pass").click(function(){
		$.ajax({
			type:"POST",
			url:"seeAuthority",
			//success:
			data:{
				target:'1',
			}
		});
	});
})
$(function(){
	$("#unPass").click(function(){
		$.ajax({
			type:"POST",
			url:"seeAuthority",
			//success:
			data:{
				target:'2',
			}
		});
	});
})